id: A48897657
initial_creation_type: input
imported: '2022-06-29T10:11:20.623541'
last_modified: '2022-06-29T10:11:20.623554'
parser: null
source_metadata:
  creation_method: proof_reading
  source : D3874
  title: chonjuk
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
